name: calculator1
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animated_theme_switcher: ^2.0.7
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  math_expressions: ^2.3.1
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
